import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
    console.log('🌱 Starting database seed...');

    // Remove admin demo credentials display
    const hashedPassword = await bcrypt.hash('admin123', 10);
    const admin = await prisma.user.upsert({
        where: { email: 'admin@layl.in' },
        update: {},
        create: {
            email: 'admin@layl.in',
            name: 'LAYL Admin',
            password: hashedPassword,
            role: 'ADMIN',
        },
    });
    console.log('✅ Admin user created');

    // Create categories
    const categories = [
        {
            name: 'Cleanser & Toner',
            slug: 'cleanser',
            description: 'Gentle cleansers and pH-balancing toners',
            accentColor: '#8B9A8B',
        },
        {
            name: 'Acne & Exfoliation',
            slug: 'acne',
            description: 'Targeted treatments for acne and chemical exfoliation',
            accentColor: '#A67C7C',
        },
        {
            name: 'Hydration & Barrier',
            slug: 'hydration',
            description: 'Moisturizers and barrier repair formulations',
            accentColor: '#7B8FA3',
        },
        {
            name: 'Sunscreen',
            slug: 'sunscreen',
            description: 'Broad-spectrum UV protection',
            accentColor: '#C9B896',
        },
        {
            name: 'Anti-Aging',
            slug: 'antiaging',
            description: 'Retinoids and peptide formulations',
            accentColor: '#9B8B9B',
        },
        {
            name: 'Body Care',
            slug: 'bodycare',
            description: 'Body treatments and moisturizers',
            accentColor: '#8B8B8B',
        },
    ];

    for (const category of categories) {
        await prisma.category.upsert({
            where: { slug: category.slug },
            update: {},
            create: category,
        });
    }
    console.log('✅ Categories created');

    // Get all category IDs
    const cleanserCat = await prisma.category.findUnique({ where: { slug: 'cleanser' } });
    const hydrationCat = await prisma.category.findUnique({ where: { slug: 'hydration' } });
    const acneCat = await prisma.category.findUnique({ where: { slug: 'acne' } });
    const sunscreenCat = await prisma.category.findUnique({ where: { slug: 'sunscreen' } });
    const antiagingCat = await prisma.category.findUnique({ where: { slug: 'antiaging' } });
    const bodycareCat = await prisma.category.findUnique({ where: { slug: 'bodycare' } });

    // Comprehensive product catalog with placeholder images (Unsplash)
    const products = [
        // CLEANSER & TONER (5 products)
        {
            name: 'Salicylic Acid Cleanser',
            slug: 'salicylic-acid-cleanser',
            description: 'Gentle foaming cleanser with 0.5% salicylic acid for daily acne prevention.',
            keyIngredients: ['Salicylic Acid 0.5%', 'Glycerin'],
            concentration: '0.5%',
            skinType: ['Oily', 'Acne-Prone', 'Combination'],
            whatItDoes: 'Cleanses while preventing breakouts and minimizing pores',
            howToUse: 'Use morning and evening. Massage onto damp face, rinse thoroughly.',
            fullIngredients: 'Aqua, Cocamidopropyl Betaine, Salicylic Acid, Glycerin, Sodium Chloride, Citric Acid, Phenoxyethanol',
            price: 399,
            mrp: 549,
            size: '100ml',
            stock: 150,
            categoryId: cleanserCat!.id,
            images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400',
            featured: true,
            isActive: true,
        },
        {
            name: 'Gentle Cream Cleanser',
            slug: 'gentle-cream-cleanser',
            description: 'Ultra-gentle, non-foaming cream cleanser for sensitive and dry skin.',
            keyIngredients: ['Ceramides', 'Squalane'],
            concentration: null,
            skinType: ['Dry', 'Sensitive', 'Normal'],
            whatItDoes: 'Gently removes impurities while maintaining skin barrier',
            howToUse: 'Massage onto dry or damp skin, rinse with lukewarm water.',
            fullIngredients: 'Aqua, Glycerin, Cetearyl Alcohol, Squalane, Ceramide NP, Phenoxyethanol',
            price: 449,
            mrp: 599,
            size: '100ml',
            stock: 120,
            categoryId: cleanserCat!.id,
            images: ['https://images.unsplash.com/photo-1571875257727-256c39da42af?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=400',
            featured: false,
            isActive: true,
        },
        {
            name: 'Hyaluronic Acid Toner',
            slug: 'hyaluronic-acid-toner',
            description: 'Hydrating toner with multiple molecular weights of hyaluronic acid.',
            keyIngredients: ['Hyaluronic Acid', 'Glycerin'],
            concentration: '2%',
            skinType: ['All Skin Types', 'Dehydrated'],
            whatItDoes: 'Hydrates and preps skin for better absorption',
            howToUse: 'Apply to clean skin with hands or cotton pad.',
            fullIngredients: 'Aqua, Sodium Hyaluronate, Glycerin, Pentylene Glycol, Phenoxyethanol',
            price: 349,
            mrp: 499,
            size: '150ml',
            stock: 200,
            categoryId: cleanserCat!.id,
            images: ['https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=400',
            featured: false,
            isActive: true,
        },
        {
            name: 'Niacinamide Toner',
            slug: 'niacinamide-toner',
            description: 'Clarifying toner with 5% niacinamide for pore refinement.',
            keyIngredients: ['Niacinamide 5%', 'Zinc PCA'],
            concentration: '5%',
            skinType: ['Oily', 'Combination', 'Acne-Prone'],
            whatItDoes: 'Minimizes pores, controls sebum, evens skin tone',
            howToUse: 'Apply after cleansing, before serums. Use AM and PM.',
            fullIngredients: 'Aqua, Niacinamide, Zinc PCA, Pentylene Glycol, Phenoxyethanol',
            price: 449,
            mrp: 599,
            size: '150ml',
            stock: 180,
            categoryId: cleanserCat!.id,
            images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400',
            featured: false,
            isActive: true,
        },
        {
            name: 'Micellar Water',
            slug: 'micellar-water',
            description: 'Gentle makeup remover and cleanser for all skin types.',
            keyIngredients: ['Micelles', 'Panthenol'],
            concentration: null,
            skinType: ['All Skin Types', 'Sensitive'],
            whatItDoes: 'Removes makeup, dirt, and oil without rinsing',
            howToUse: 'Apply to cotton pad and wipe across face.',
            fullIngredients: 'Aqua, Glycerin, Poloxamer 184, Panthenol, Phenoxyethanol',
            price: 299,
            mrp: 399,
            size: '200ml',
            stock: 250,
            categoryId: cleanserCat!.id,
            images: ['https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=400',
            featured: false,
            isActive: true,
        },

        // ACNE & EXFOLIATION (6 products)
        {
            name: 'Salicylic Acid 2%',
            slug: 'salicylic-acid-2',
            description: 'BHA for treating acne, unclogging pores, and gentle exfoliation.',
            keyIngredients: ['Salicylic Acid'],
            concentration: '2%',
            skinType: ['Oily', 'Acne-Prone', 'Combination'],
            whatItDoes: 'Exfoliates inside pores, reduces acne and blackheads',
            howToUse: 'Apply to clean skin in PM. Start 2-3 times per week.',
            fullIngredients: 'Aqua, Salicylic Acid, Hamamelis Virginiana Water, Glycerin, Phenoxyethanol',
            price: 549,
            mrp: 749,
            size: '30ml',
            stock: 100,
            categoryId: acneCat!.id,
            images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400',
            featured: true,
            isActive: true,
        },
        {
            name: 'Glycolic Acid 7% Toner',
            slug: 'glycolic-acid-7-toner',
            description: 'AHA toner for surface exfoliation and brightening.',
            keyIngredients: ['Glycolic Acid 7%', 'Aloe Vera'],
            concentration: '7%',
            skinType: ['Normal', 'Dry', 'Combination'],
            whatItDoes: 'Exfoliates dead skin cells, improves texture',
            howToUse: 'Apply in PM after cleansing. Use 2-3 times per week.',
            fullIngredients: 'Aqua, Glycolic Acid, Aloe Barbadensis Leaf Juice, Glycerin, Phenoxyethanol',
            price: 499,
            mrp: 649,
            size: '100ml',
            stock: 130,
            categoryId: acneCat!.id,
            images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400',
            featured: false,
            isActive: true,
        },
        {
            name: 'Niacinamide 10% + Zinc 1%',
            slug: 'niacinamide-10-zinc-1',
            description: 'High-strength niacinamide with zinc for blemish control.',
            keyIngredients: ['Niacinamide 10%', 'Zinc PCA 1%'],
            concentration: '10%',
            skinType: ['Oily', 'Acne-Prone', 'Combination'],
            whatItDoes: 'Reduces blemishes, minimizes pores, controls oil',
            howToUse: 'Apply to entire face morning and evening.',
            fullIngredients: 'Aqua, Niacinamide, Zinc PCA, Pentylene Glycol, Phenoxyethanol',
            price: 599,
            mrp: 799,
            size: '30ml',
            stock: 150,
            categoryId: acneCat!.id,
            images: ['https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400',
            featured: true,
            isActive: true,
        },
        {
            name: 'Azelaic Acid 10%',
            slug: 'azelaic-acid-10',
            description: 'Multi-functional treatment for acne and hyperpigmentation.',
            keyIngredients: ['Azelaic Acid 10%'],
            concentration: '10%',
            skinType: ['Oily', 'Acne-Prone', 'Sensitive'],
            whatItDoes: 'Reduces acne, fades dark spots, evens skin tone',
            howToUse: 'Apply to clean skin once or twice daily.',
            fullIngredients: 'Aqua, Azelaic Acid, Glycerin, Propanediol, Dimethicone, Phenoxyethanol',
            price: 649,
            mrp: 849,
            size: '30ml',
            stock: 90,
            categoryId: acneCat!.id,
            images: ['https://images.unsplash.com/photo-1556228841-a5c4c2a19d96?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1556228841-a5c4c2a19d96?w=400',
            featured: false,
            isActive: true,
        },
        {
            name: 'Lactic Acid 5% + HA',
            slug: 'lactic-acid-5-ha',
            description: 'Gentle AHA with hyaluronic acid for mild exfoliation.',
            keyIngredients: ['Lactic Acid 5%', 'Hyaluronic Acid'],
            concentration: '5%',
            skinType: ['Dry', 'Sensitive', 'Normal'],
            whatItDoes: 'Gently exfoliates while hydrating the skin',
            howToUse: 'Apply in PM after cleansing. Use 2-4 times weekly.',
            fullIngredients: 'Aqua, Lactic Acid, Sodium Hyaluronate, Glycerin, Phenoxyethanol',
            price: 449,
            mrp: 599,
            size: '30ml',
            stock: 110,
            categoryId: acneCat!.id,
            images: ['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400',
            featured: false,
            isActive: true,
        },
        {
            name: 'Mandelic Acid 10%',
            slug: 'mandelic-acid-10',
            description: 'Gentle AHA suitable for sensitive skin.',
            keyIngredients: ['Mandelic Acid 10%'],
            concentration: '10%',
            skinType: ['Sensitive', 'All Skin Types'],
            whatItDoes: 'Exfoliates gently, improves texture',
            howToUse: 'Apply in PM. Can be used 3-4 times weekly.',
            fullIngredients: 'Aqua, Mandelic Acid, Glycerin, Pentylene Glycol, Phenoxyethanol',
            price: 499,
            mrp: 649,
            size: '30ml',
            stock: 95,
            categoryId: acneCat!.id,
            images: ['https://images.unsplash.com/photo-1612817288484-6f916006741a?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=400',
            featured: false,
            isActive: true,
        },

        // HYDRATION & BARRIER (6 products)
        {
            name: 'Hyaluronic Acid 2% + B5',
            slug: 'hyaluronic-acid-2-b5',
            description: 'Multi-molecular weight HA with vitamin B5 for deep hydration.',
            keyIngredients: ['Hyaluronic Acid', 'Panthenol (Vitamin B5)'],
            concentration: '2%',
            skinType: ['All Skin Types', 'Dry', 'Dehydrated'],
            whatItDoes: 'Provides multi-layer hydration and supports skin barrier',
            howToUse: 'Apply to damp skin morning and evening.',
            fullIngredients: 'Aqua, Sodium Hyaluronate, Panthenol, Pentylene Glycol, Phenoxyethanol',
            price: 499,
            mrp: 699,
            size: '30ml',
            stock: 100,
            categoryId: hydrationCat!.id,
            images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400',
            featured: true,
            isActive: true,
        },
        {
            name: 'Natural Moisturizing Factors + HA',
            slug: 'nmf-ha',
            description: 'Surface hydration formula with amino acids and HA.',
            keyIngredients: ['Amino Acids', 'Sodium PCA', 'HA'],
            concentration: null,
            skinType: ['Dry', 'Normal', 'Dehydrated'],
            whatItDoes: 'Replenishes skin\'s natural moisturizing components',
            howToUse: 'Apply to face morning and evening.',
            fullIngredients: 'Aqua, Glycerin, Sodium PCA, Sodium Lactate, Sodium Hyaluronate, Phenoxyethanol',
            price: 449,
            mrp: 599,
            size: '30ml',
            stock: 140,
            categoryId: hydrationCat!.id,
            images: ['https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400',
            featured: false,
            isActive: true,
        },
        {
            name: 'Ceramide Barrier Cream',
            slug: 'ceramide-barrier-cream',
            description: 'Rich moisturizer with ceramides for barrier repair.',
            keyIngredients: ['Ceramides', 'Cholesterol', 'Fatty Acids'],
            concentration: null,
            skinType: ['Dry', 'Sensitive', 'Compromised Barrier'],
            whatItDoes: 'Repairs and strengthens skin barrier',
            howToUse: 'Apply as final step morning and evening.',
            fullIngredients: 'Aqua, Glycerin, Ceramide NP, Cholesterol, Dimethicone, Phenoxyethanol',
            price: 699,
            mrp: 899,
            size: '50ml',
            stock: 85,
            categoryId: hydrationCat!.id,
            images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400',
            featured: false,
            isActive: true,
        },
        {
            name: 'Squalane 100%',
            slug: 'squalane-100',
            description: 'Pure plant-derived squalane oil for lightweight hydration.',
            keyIngredients: ['Squalane 100%'],
            concentration: '100%',
            skinType: ['All Skin Types', 'Dry'],
            whatItDoes: 'Locks in moisture, supports barrier function',
            howToUse: 'Apply 2-3 drops to face morning or evening.',
            fullIngredients: 'Squalane',
            price: 599,
            mrp: 799,
            size: '30ml',
            stock: 120,
            categoryId: hydrationCat!.id,
            images: ['https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=400',
            featured: false,
            isActive: true,
        },
        {
            name: 'Centella Asiatica Serum',
            slug: 'centella-serum',
            description: 'Soothing serum with cica extract for sensitive skin.',
            keyIngredients: ['Centella Asiatica 10%', 'Madecassoside'],
            concentration: '10%',
            skinType: ['Sensitive', 'Irritated', 'All Skin Types'],
            whatItDoes: 'Soothes irritation, promotes healing',
            howToUse: 'Apply to clean skin morning and evening.',
            fullIngredients: 'Aqua, Centella Asiatica Extract, Madecassoside, Glycerin, Phenoxyethanol',
            price: 549,
            mrp: 749,
            size: '30ml',
            stock: 100,
            categoryId: hydrationCat!.id,
            images: ['https://images.unsplash.com/photo-1571875257727-256c39da42af?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=400',
            featured: false,
            isActive: true,
        },
        {
            name: 'Peptide Complex Serum',
            slug: 'peptide-complex',
            description: 'Multi-peptide formula for hydration and firmness.',
            keyIngredients: ['Matrixyl 3000', 'Argireline'],
            concentration: null,
            skinType: ['All Skin Types', 'Mature'],
            whatItDoes: 'Improves firmness, hydration, supports collagen',
            howToUse: 'Apply to face and neck morning and evening.',
            fullIngredients: 'Aqua, Palmitoyl Tripeptide-1, Acetyl Hexapeptide-8, Glycerin, Phenoxyethanol',
            price: 799,
            mrp: 999,
            size: '30ml',
            stock: 75,
            categoryId: hydrationCat!.id,
            images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400',
            featured: false,
            isActive: true,
        },

        // SUNSCREEN (5 products)
        {
            name: 'SPF 50 PA++++ Sunscreen',
            slug: 'spf-50-sunscreen',
            description: 'Broad-spectrum hybrid sunscreen with high UVA/UVB protection.',
            keyIngredients: ['Zinc Oxide', 'Tinosorb S'],
            concentration: 'SPF 50 PA++++',
            skinType: ['All Skin Types'],
            whatItDoes: 'Provides broad-spectrum sun protection',
            howToUse: 'Apply generously as last step. Reapply every 2 hours.',
            fullIngredients: 'Aqua, Zinc Oxide, Ethylhexyl Methoxycinnamate, Bemotrizinol, Glycerin, Phenoxyethanol',
            price: 599,
            mrp: 799,
            size: '50ml',
            stock: 100,
            categoryId: sunscreenCat!.id,
            images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400',
            featured: true,
            isActive: true,
        },
        {
            name: 'Mineral SPF 30 Tinted',
            slug: 'mineral-spf-30-tinted',
            description: '100% mineral sunscreen with subtle tint.',
            keyIngredients: ['Zinc Oxide 15%', 'Titanium Dioxide 5%'],
            concentration: 'SPF 30 PA+++',
            skinType: ['All Skin Types', 'Sensitive'],
            whatItDoes: 'Physical sun protection with sheer coverage',
            howToUse: 'Shake well. Apply evenly before sun exposure.',
            fullIngredients: 'Aqua, Zinc Oxide, Titanium Dioxide, Iron Oxides, Squalane, Phenoxyethanol',
            price: 649,
            mrp: 849,
            size: '50ml',
            stock: 80,
            categoryId: sunscreenCat!.id,
            images: ['https://images.unsplash.com/photo-1571875257727-256c39da42af?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=400',
            featured: false,
            isActive: true,
        },
        {
            name: 'Ultra-Light SPF 50+',
            slug: 'ultra-light-spf-50',
            description: 'Invisible finish chemical sunscreen for oily skin.',
            keyIngredients: ['Tinosorb M', 'Uvinul T 150'],
            concentration: 'SPF 50+ PA++++',
            skinType: ['Oily', 'Combination', 'Acne-Prone'],
            whatItDoes: 'Matte finish sun protection that controls oil',
            howToUse: 'Apply 15 minutes before sun exposure.',
            fullIngredients: 'Aqua, Ethylhexyl Triazone, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Silica, Phenoxyethanol',
            price: 549,
            mrp: 749,
            size: '50ml',
            stock: 130,
            categoryId: sunscreenCat!.id,
            images: ['https://images.unsplash.com/photo-1556228841-a5c4c2a19d96?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1556228841-a5c4c2a19d96?w=400',
            featured: false,
            isActive: true,
        },
        {
            name: 'Hydrating SPF 30',
            slug: 'hydrating-spf-30',
            description: 'Moisturizing sunscreen with hyaluronic acid.',
            keyIngredients: ['Avobenzone', 'Hyaluronic Acid'],
            concentration: 'SPF 30 PA+++',
            skinType: ['Dry', 'Normal'],
            whatItDoes: 'Sun protection while hydrating the skin',
            howToUse: 'Apply before sun exposure.',
            fullIngredients: 'Aqua, Butyl Methoxydibenzoylmethane, Sodium Hyaluronate, Glycerin, Phenoxyethanol',
            price: 499,
            mrp: 649,
            size: '50ml',
            stock: 110,
            categoryId: sunscreenCat!.id,
            images: ['https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=400',
            featured: false,
            isActive: true,
        },
        {
            name: 'Kids Mineral Sunscreen SPF 50',
            slug: 'kids-mineral-spf-50',
            description: 'Gentle 100% mineral sunscreen for children.',
            keyIngredients: ['Zinc Oxide 20%'],
            concentration: 'SPF 50 PA++++',
            skinType: ['Sensitive', 'Children'],
            whatItDoes: 'Safe sun protection for delicate skin',
            howToUse: 'Apply generously before sun exposure.',
            fullIngredients: 'Aqua, Zinc Oxide, Glycerin, Panthenol, Phenoxyethanol',
            price: 699,
            mrp: 899,
            size: '75ml',
            stock: 90,
            categoryId: sunscreenCat!.id,
            images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400',
            featured: false,
            isActive: true,
        },

        // ANTI-AGING (5 products)
        {
            name: 'Retinol 0.5% in Squalane',
            slug: 'retinol-05-squalane',
            description: 'Moderate-strength retinol for fine lines and texture.',
            keyIngredients: ['Retinol 0.5%', 'Squalane'],
            concentration: '0.5%',
            skinType: ['Normal', 'Dry', 'Mature'],
            whatItDoes: 'Reduces fine lines, improves texture, boosts collagen',
            howToUse: 'Apply in PM only. Start 2x weekly. Use SPF daily.',
            fullIngredients: 'Squalane, Retinol, Caprylic/Capric Triglyceride, BHT, Tocopherol',
            price: 899,
            mrp: 1199,
            size: '30ml',
            stock: 60,
            categoryId: antiagingCat!.id,
            images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400',
            featured: true,
            isActive: true,
        },
        {
            name: 'Granactive Retinoid 2% Emulsion',
            slug: 'granactive-retinoid-2',
            description: 'Next-generation retinoid with reduced irritation.',
            keyIngredients: ['Hydroxypinacolone Retinoate 2%'],
            concentration: '2%',
            skinType: ['All Skin Types', 'Sensitive'],
            whatItDoes: 'Anti-aging benefits with less irritation',
            howToUse: 'Apply in PM after water-based serums.',
            fullIngredients: 'Aqua, Hydroxypinacolone Retinoate, Squalane, Glycerin, Phenoxyethanol',
            price: 799,
            mrp: 999,
            size: '30ml',
            stock: 70,
            categoryId: antiagingCat!.id,
            images: ['https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400',
            featured: false,
            isActive: true,
        },
        {
            name: 'Vitamin C 23% + HA Spheres',
            slug: 'vitamin-c-23-ha',
            description: 'High-strength vitamin C for advanced brightening.',
            keyIngredients: ['L-Ascorbic Acid 23%', 'HA'],
            concentration: '23%',
            skinType: ['Normal', 'Dry'],
            whatItDoes: 'Brightens, protects from free radicals',
            howToUse: 'Apply in AM or PM. May cause tingling.',
            fullIngredients: 'Ascorbic Acid, Squalane, Sodium Hyaluronate, Tocopherol',
            price: 849,
            mrp: 1099,
            size: '30ml',
            stock: 55,
            categoryId: antiagingCat!.id,
            images: ['https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400',
            featured: false,
            isActive: true,
        },
        {
            name: 'Matrixyl 10% + HA',
            slug: 'matrixyl-10-ha',
            description: 'Peptide serum targeting wrinkles and firmness.',
            keyIngredients: ['Palmitoyl Tripeptide-1'],
            concentration: '10%',
            skinType: ['All Skin Types', 'Mature'],
            whatItDoes: 'Reduces wrinkle depth, improves firmness',
            howToUse: 'Apply to face and neck morning and evening.',
            fullIngredients: 'Aqua, Palmitoyl Tripeptide-1, Glycerin, Sodium Hyaluronate, Phenoxyethanol',
            price: 749,
            mrp: 949,
            size: '30ml',
            stock: 80,
            categoryId: antiagingCat!.id,
            images: ['https://images.unsplash.com/photo-1571875257727-256c39da42af?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=400',
            featured: false,
            isActive: true,
        },
        {
            name: 'Resveratrol 3% + Ferulic Acid 3%',
            slug: 'resveratrol-3-ferulic-3',
            description: 'Antioxidant powerhouse for environmental protection.',
            keyIngredients: ['Resveratrol 3%', 'Ferulic Acid 3%'],
            concentration: '3% + 3%',
            skinType: ['All Skin Types'],
            whatItDoes: 'Protects against environmental damage',
            howToUse: 'Apply in PM before oils/creams.',
            fullIngredients: 'Propanediol, Resveratrol, Ferulic Acid, Glycerin, Phenoxyethanol',
            price: 699,
            mrp: 899,
            size: '30ml',
            stock: 65,
            categoryId: antiagingCat!.id,
            images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400',
            featured: false,
            isActive: true,
        },

        // BODY CARE (5 products)
        {
            name: 'Glycolic Acid 7% Body Lotion',
            slug: 'glycolic-body-lotion',
            description: 'Exfoliating body lotion for smooth skin.',
            keyIngredients: ['Glycolic Acid 7%', 'Shea Butter'],
            concentration: '7%',
            skinType: ['All Skin Types', 'Rough Texture'],
            whatItDoes: 'Exfoliates dead skin, smooths texture',
            howToUse: 'Apply to body after shower. Use SPF on exposed areas.',
            fullIngredients: 'Aqua, Glycolic Acid, Butyrospermum Parkii Butter, Glycerin, Phenoxyethanol',
            price: 649,
            mrp: 849,
            size: '200ml',
            stock: 100,
            categoryId: bodycareCat!.id,
            images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400',
            featured: false,
            isActive: true,
        },
        {
            name: 'Salicylic Acid 2% Body Spray',
            slug: 'salicylic-body-spray',
            description: 'Targeted treatment for body acne.',
            keyIngredients: ['Salicylic Acid 2%', 'Niacinamide'],
            concentration: '2%',
            skinType: ['Oily', 'Acne-Prone'],
            whatItDoes: 'Treats body acne, unclogs pores',
            howToUse: 'Spray on affected areas after shower.',
            fullIngredients: 'Aqua, Alcohol Denat., Salicylic Acid, Niacinamide, Phenoxyethanol',
            price: 549,
            mrp: 749,
            size: '100ml',
            stock: 85,
            categoryId: bodycareCat!.id,
            images: ['https://images.unsplash.com/photo-1571875257727-256c39da42af?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=400',
            featured: false,
            isActive: true,
        },
        {
            name: 'Rich Body Cream',
            slug: 'rich-body-cream',
            description: 'Intensive moisturizer for very dry skin.',
            keyIngredients: ['Ceramides', 'Urea 5%', 'Shea Butter'],
            concentration: null,
            skinType: ['Very Dry', 'Eczema-Prone'],
            whatItDoes: 'Deeply moisturizes, repairs barrier',
            howToUse: 'Apply generously to body after bathing.',
            fullIngredients: 'Aqua, Urea, Butyrospermum Parkii Butter, Ceramide NP, Glycerin, Phenoxyethanol',
            price: 599,
            mrp: 799,
            size: '200ml',
            stock: 120,
            categoryId: bodycareCat!.id,
            images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400',
            featured: false,
            isActive: true,
        },
        {
            name: 'Hand Cream SPF 15',
            slug: 'hand-cream-spf-15',
            description: 'Protective hand cream with SPF.',
            keyIngredients: ['SPF 15', 'Niacinamide', 'Glycerin'],
            concentration: 'SPF 15',
            skinType: ['All Skin Types'],
            whatItDoes: 'Moisturizes hands while protecting from sun',
            howToUse: 'Apply throughout the day after washing hands.',
            fullIngredients: 'Aqua, Ethylhexyl Methoxycinnamate, Glycerin, Niacinamide, Phenoxyethanol',
            price: 349,
            mrp: 449,
            size: '75ml',
            stock: 150,
            categoryId: bodycareCat!.id,
            images: ['https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=400',
            featured: false,
            isActive: true,
        },
        {
            name: 'Exfoliating Body Scrub',
            slug: 'exfoliating-body-scrub',
            description: 'Physical exfoliant with jojoba beads.',
            keyIngredients: ['Jojoba Esters', 'Glycerin'],
            concentration: null,
            skinType: ['All Skin Types'],
            whatItDoes: 'Gently buffs away dead skin',
            howToUse: 'Use 1-2 times weekly in shower.',
            fullIngredients: 'Aqua, Jojoba Esters, Glycerin, Cellulose, Phenoxyethanol',
            price: 499,
            mrp: 649,
            size: '150ml',
            stock: 95,
            categoryId: bodycareCat!.id,
            images: ['https://images.unsplash.com/photo-1556228841-a5c4c2a19d96?w=400'],
            thumbnailUrl: 'https://images.unsplash.com/photo-1556228841-a5c4c2a19d96?w=400',
            featured: false,
            isActive: true,
        },
    ];

    for (const product of products) {
        await prisma.product.upsert({
            where: { slug: product.slug },
            update: {},
            create: product,
        });
    }
    console.log(`✅ ${products.length} Products created`);

    // Create sample coupon
    await prisma.coupon.upsert({
        where: { code: 'WELCOME10' },
        update: {},
        create: {
            code: 'WELCOME10',
            description: 'Welcome discount - 10% off',
            discountType: 'PERCENTAGE',
            value: 10,
            minPurchase: 500,
            maxDiscount: 200,
            usageLimit: 1000,
            validFrom: new Date(),
            validUntil: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
            isActive: true,
        },
    });
    console.log('✅ Coupon created');

    console.log('🎉 Database seeded successfully!');
}

main()
    .catch((e) => {
        console.error('❌ Error seeding database:', e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
